name: firestore_doc
description: A new Flutter package project.
version: 0.0.1
author: Dustin Graham
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: ^4.3.2
  built_value: ^7.0.8

dev_dependencies:
  built_value_generator: ^7.0.8
  build_runner: ^1.11.1

dependency_overrides:
  analyzer: 0.41.2