name: firestore_doc
description: A new Flutter package project.
version: 0.0.1
author: Dustin Graham
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.2

dev_dependencies:
  built_value_generator: ^8.9.2
  build_runner: ^2.4.9